; SPDX-License-Identifier: GPL-3.0-only
; Fixture for TC-07: license text embedded in a non-.php file type (.ini instead of composer.json,
; to avoid breaking the real composer.json used by the Trivy test cases).

[app]
name = "php-sample-testcase"
